
import com.socket.ServerFrame;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JRootPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIVAM
 */
public class wel extends javax.swing.JFrame {

    /** Creates new form wel */
    public wel() {
        this.setContentPane(new JLabel(new ImageIcon("welcom.jpg")));
        
        initComponents();
        this.setUndecorated(true);
//this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
       //  jprog.set
        new Thread(new myt()).start();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jprog = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinema Ticket Management System");
        setResizable(false);
        getContentPane().setLayout(null);

        jprog.setBackground(new java.awt.Color(51, 153, 255));
        jprog.setPreferredSize(new java.awt.Dimension(150, 10));
        getContentPane().add(jprog);
        jprog.setBounds(0, 290, 640, 3);

        setSize(new java.awt.Dimension(655, 299));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wel().setVisible(true);
            }
        });
    }
    class myt implements Runnable{

        @Override
        public void run() {
            try{
            for(int i=0;i<=100;i++)
            {
        jprog.setValue(i);
        Thread.sleep(35);        
            }
            new ServerFrame().setVisible(true);
            dispose();
        }
            catch(Exception e){
            e.printStackTrace();
        }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jprog;
    // End of variables declaration//GEN-END:variables

}
